version: "3"
services:
  proxy:
    image: "zhi:1"
    container_name: proxy
    networks:
      - default
      - app_net
    ports:
      - "3000:3000"
    volumes:
      - "./.:/app/src/apis"
    restart: always
networks:
  app_net:
    external: true
